# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_polltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
